### ISSUE TITLE
Display cluster IP address on dashboard

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#251]
- [ ] AWS
- [ ] GCP
- [ ] DO

**Comment by jnfrati** [comment]
Hey, I'm kinda new around here, and in order to get used to all the environment I was thinking that this could be shown like this
![image](https://user-images.githubusercontent.com/23369263/119542670-2f21f300-bd66-11eb-84a4-0c641b82958b.png)

The idea would be that the user is able to click anywhere on the link and copy it to the clipboard, as the URLs could be too long to be shown, and select it would make the dashboard go to the apps page.

Let me know if you like it and I'll open a PR!

**Comment by abelanger5** [comment]
Thanks @jnfrati, looks great! Please go ahead and make a PR (just link this issue in the PR template) and I'll review it ASAP.

**Comment by jnfrati** [comment]
Great! I have one more question, I don't know what your target browsers are and if this should be available for Safari too. If it should be compatible, I would like to add the [clipboardjs](https://clipboardjs.com/) package to keep it simple and support almost all environments.

**Comment by abelanger5** [comment]
Yes @jnfrati, good catch. Perhaps you can create a shared component with copy-to-clipboard functionality using clipboardjs? There are two other places where we currently copy to clipboard (`SettingsSection.tsx` and `InviteList.tsx`), and it would be good to consolidate.

**Comment by jnfrati** [comment]
Okay, I'll try to cover those too to keep the clipboard usage consistent
