### ISSUE TITLE
Urgent - Stop Creating Droplets Without Consent

### ISSUE THREAD

**Issue by dougwithseismic** [porter-dev/porter#349]
Porter keeps provisioning new droplets on my digital ocean account - Every time I destroy, it provisions another. 
I'm getting billed for these!

**Comment by abelanger5** [comment]
Hi @dougwithseismic -- we provision a Kubernetes cluster on DigitalOcean. If you are trying to destroy the droplets, it is DigitalOcean that is creating new droplets, since it tries to maintain a certain number of droplets running for the Kubernetes service. In order to remove the droplets permanently and stop getting billed, you must delete the Kubernetes cluster. This can be done by navigating to the Kubernetes tab in the DigitalOcean dashboard, clicking on the cluster, going to Settings, and clicking "Destroy."

Apologies if this was unclear. Would it help to add a notice in the documentation? I saw you closed the issue, but I can reopen if there's a change we can make on the platform.
