### ISSUE TITLE
Renaming an Environment Group

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#841]
# Location

- [x] Browser
- [ ] CLI
- [x] API

# Motivation
# Requirements
Users should be able to rename an existing environment group

# Additional Details

**Comment by anukul** [comment]
Hi! I'm interested in working on this.

**Comment by abelanger5** [comment]
Sounds good @anukul! 

I assigned it to you, but this will involve some complicated changes on the backend. I believe you will have to copy each configmap/secret to a new object in order to rename the environment group, since names are immutable in Kubernetes. It would be best to create a "Draft PR" with the proposed implementation before you dive in :)
