### ISSUE TITLE
[dev-environment] docker-compose renders older version of the app on browser

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#87]
`docker-compose -f docker-compose.dev.yaml up` doesn't hot reload on a normal browser session and instead runs an older image. It properly hot reloads on incognito.

**Comment by abelanger5** [comment]
Hard clear the cache and reload this page -- in Chrome, open devtools and then hold down the refresh button and select "Empty Cache and Hard Reload". 

For some explanation, this is because the `Last-Modified` headers after running `http.FileServer` in the releases don't match with the headers sent by the webpack server (these likely are not sent by webpack at all).
