### ISSUE TITLE
Horizontal pod autoscaling on application metrics

### ISSUE THREAD

**Issue by jnfrati** [porter-dev/porter#898]
# Location

- [x] Browser
- [ ] CLI
- [x] API

# Requirements

The application tab metrics should be able to display when the autoscaling of pods is occurring, for this, I propose 2 new charts and an update to the current ones: 

### The images are illustrative and can vary when the feature is implemented

The first image corresponds to an update of the current metrics. The idea would be to show the user when the next autoscaling will occur 
![Update to RAM/CPU charts](https://user-images.githubusercontent.com/23369263/126165150-50ff9c7c-947e-486d-990f-202c474a3169.png)

This chart should show the user the historical number of replicas that the application used.
![Amount of replicas chart](https://user-images.githubusercontent.com/23369263/126165163-411a9dc8-3b27-40a3-846f-22c9659da818.png)

These two charts can be combined in a single one with just a type selector, but the idea is to show the average usage across all pods and when the application is reaching the autoscaling top.
![Average CPU usage chart](https://user-images.githubusercontent.com/23369263/126165180-d76801fe-d66f-4bfa-a49b-f3f75b247b21.png)
![Average RAM usage chart](https://user-images.githubusercontent.com/23369263/126165209-8ac2d3cc-73ac-49b4-927c-72ffc1d3a4f9.png)

**Comment by abelanger5** [comment]
After some digging, it seems that we can implement this with the following:
1. (first graph) To get persistent usage for all pods, we can construct a regex for controllers that essentially looks like the following:

```
Deployment: <deployment_name>-[a-z0-9]+-[a-z0-9]+
Statefulset: <stateful_set_name>-[0-9]+
Cronjob: <cron_job_name>-[a-z0-9]+-[a-z0-9]+
Job:  <job_name>-[a-z0-9]+
```

For example, the Prometheus query for a deployment named `test-web` in namespace `default` would be:

```
sum(rate(container_cpu_usage_seconds_total{namespace="default",pod=~"test-web-[a-z0-9]+-[a-z0-9]+",container="POD",container!=""`}[5m]))
``` 

This should resolve #472 and #787 

2. If HPA is enabled, we can use the [`kube-state-metrics` data](https://github.com/kubernetes/kube-state-metrics/blob/release-1.9/docs/horizontalpodautoscaler-metrics.md) to get the number of replicas for each point in time with `kube_hpa_status_current_replicas`, the threshold at each point in time via `kube_hpa_status_condition`, and the resource request at each point in time via `kube_pod_container_resource_requests_<resource>`. The last metric is slightly challenging, because we will match all pods via the regex above, but all of the resource requests should have the same value, so we can just flatten the result to a single metric.   

Finally, to compute the threshold, we simply do:

```
num_replicas * resource_request * utilization_threshold
```

**For each moment in time**. This transformation can potentially happen on the frontend, since we can re-use some of these queries in different graphs (like the number of replicas graph). For example, 8 replicas with `500m` CPU request at a 50% threshold would result in an absolute threshold line of 2 CPUs (or `2000m`).
